[package]
name = "spam-killer"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15.7"
tokio = "1.44.2"
log = "0.4.27" 
serde_json = "1.0.140"
teloxide = "0.15.0"
pretty_env_logger = "0.5"
gemini_client_rs = "0.3.0"
uuid = "1.16.0"

