name: Deploy Spam Slayer Rust Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build the project
        run: cargo build --release

      - name: Copy binary to server (as temporary file)
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT || '22' }}
          source: "target/release/spam_slayer"
          target: "/opt/spam_slayer/spam_slayer.tmp"

      - name: Replace binary and restart service
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT || '22' }}
          script: |
            sudo mv /opt/spam_slayer/spam_slayer.tmp/target/release/spam_slayer /opt/spam_slayer/spam_slayer
            sudo systemctl restart spam_slayer.service

      - name: Notify deployment completion
        run: |
          curl -X GET "https://${{ secrets.BARK_DOMAIN }}/${{ secrets.BARK_TOKEN }}/Spam%20Slayer%20部署/任务%20${{ github.run_id }}%20执行完成?group=Span%20Slayer%20CICD"
