name: Deploy Spam Slayer

on:
  push:
    branches:
      - main  # 或你的部署分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Build in release mode
      run: cargo build --release

    - name: Upload binary to VPS
      uses: appleboy/scp-action@v0.1.6
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT || '22' }}
        source: target/release/spam_slayer
        target: /tmp/spam_slayer
        overwrite: true

    - name: Configure passwordless sudo
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT || '22' }}
        script: |
          echo "${{ secrets.VPS_USER }} ALL=(ALL) NOPASSWD: /bin/systemctl, /bin/rm, /bin/mv, /bin/chmod" | sudo tee /etc/sudoers.d/spam_slayer
          sudo chmod 440 /etc/sudoers.d/spam_slayer

    - name: Deploy and restart service
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT || '22' }}
        script: |
          echo "Stopping service..."
          sudo systemctl stop spam_slayer.service
          echo "Deploying to /opt/spam_slayer..."
          sudo rm -rf /opt/spam_slayer/*
          sudo mv /tmp/spam_slayer /opt/spam_slayer/
          sudo chmod +x /opt/spam_slayer/spam_slayer
          echo "Starting service..."
          sudo systemctl start spam_slayer.service

    - name: Notify completion
      run: |
        curl -X GET "https://bark.nas.astrian.moe/NpQY8VAcM4tiSNeMYJXr9F/Spam%20Slayer%20部署/任务%20${{ github.run_id }}%20执行完成?group=Span%20Slayer%20CICD"
